---
- hosts: dev
  become: true
  tasks:
    - name: Install docker-py python module
      ansible.builtin.pip:
        name: docker
        state: present
    
    - name: install pip3
      apt: 
         name: python3-pip 
         state: present 
    
    - name: Start the container
      docker_container:
        name: app_maven_001
        image: "apotieri/app_maven_001"
        state: started
        published_ports: 
          - 0.0.0.0:8080:8080
